accounting/urls.py
# -*- coding: utf-8 -*-
# @Author: ZhuZefeng
# @Date:   2018-12-20 17:56:56
# @Last Modified by:   ZhuZefeng
# @Last Modified time: 2018-12-27 11:46:35


"""
为应用程序accounting定义URL模式
"""

from django.urls import path, re_path
from .           import views

app_name = 'accounting'

urlpatterns = [
               #accounting程序的主页
               path('', views.index, name='index'),

               #显示所有销售订单的页面
               path('orders', views.orders, name='orders'),

               #新增销售订单的页面
               path('new_order', views.new_order, name='new_order'),

               #显示所有客户信息的页面
               path('clients', views.clients, name='clients'),

               #新增客户的页面
               path('new_client', views.new_client, name='new_client'),

               #显示所有产品信息的页面
               path('products', views.products, name='products'),

               #新增产品的页面
               #path('new_product', views. new_product, name=' new_product'),
               
              ]

homepage/urls.py
# -*- coding: utf-8 -*-
# @Author: ZhuZefeng
# @Date:   2018-11-12 12:40:26
# @Last Modified by:   ZhuZefeng
# @Last Modified time: 2018-11-12 12:40:40


"""
为应用程序lhomepage定义URL模式
"""

from django.urls import path
from .           import views

app_name = 'homepage'

urlpatterns = [
               #网站的主页
               path('',views.homepage, name='homepage'),
              ]

project_orion/urls.py
from django.contrib import admin
from django.urls    import path, include

urlpatterns = [
               path('', include('homepage.urls', namespace='homepage')),
               path('admin/', admin.site.urls),
               path('users/', include('users.urls', namespace='users')),
               path('learning_logs/', include('learning_logs.urls', namespace='learning_logs')),
               path('financial_indicator_library/', include('financial_indicator_library.urls', namespace='financial_indicator_library')),
               path('accounting/', include('accounting.urls', namespace='accounting')),
              ]

users/urls.py
# -*- coding: utf-8 -*-
# @Author: ZhuZefeng
# @Date:   2018-11-01 16:59:13
# @Last Modified by:   ZhuZefeng
# @Last Modified time: 2018-11-02 18:09:50


"""为应用程序users定义URL模式"""
from django.contrib.auth.views import LoginView
from django.urls               import path
from .                         import views

app_name = 'users'

urlpatterns = [
               # 登录页面
               path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),

               #注销页面
               path('logout', views.logout_view, name='logout'),

               #注册页面
               path('register', views.register, name='register'),

              ]

accounting/models.py
from django.db import models

# Create your models here.
#在此处创建你的模型。

class Order(models.Model):
    """销售订单数据"""
    number_of_purchase_contract = models.CharField(max_length=15)
    number_of_client            = models.CharField(max_length=8 )
    product                     = models.CharField(max_length=20)
    date_of_sale                = models.DateField()
    service_life                = models.IntegerField()
    sales_amount                = models.FloatField()
    tax_included_or_not         = models.BooleanField(choices=((False,'不含增值税'),(True,'含增值税')), default=False)
    invoiced_or_not             = models.BooleanField(choices=((False,'未开发票'),(True,'已开发票')), default=False)
    number_of_invoiced          = models.CharField(max_length=20)
    closed_or_not               = models.BooleanField(choices=((False,'未到期'),(True,'已到期')), default=False)

    def __str__(self):
        """返回销售订单编号"""
        return self.number_of_purchase_contract


class Client(models.Model):
    """客户数据"""
    number_of_client               = models.CharField(max_length=8 )
    name_of_client                 = models.CharField(max_length=50)
    taxpayer_identification_number = models.CharField(max_length=18)
    province                       = models.CharField(max_length=10)
    city                           = models.CharField(max_length=10)
    address                        = models.CharField(max_length=60)
    telephone                      = models.CharField(max_length=15)
    deposit_bank                   = models.CharField(max_length=50)
    bank_account                   = models.CharField(max_length=20)

    def __str__(self):
        """返回客户名称"""
        return self.name_of_client


class Product(models.Model):
    """产品信息"""
    number_of_product    = models.CharField(max_length=4 )
    name_of_product      = models.CharField(max_length=20)
    value_added_tax_rate = models.CharField(max_length=5 )

    def __str__(self):
        """返回产品名称"""
        return self.name_of_product


class Price(models.Model):
    """价格信息"""
    product      = models.ForeignKey(Product, on_delete=models.CASCADE)
    service_life = models.IntegerField(choices=((30,'30天'), (60,'60天'), (180,'180天'), (360,'360天'), (720,'720天')))
    price        = models.CharField(max_length=20)

    def __str__(self):
        """返回产品名称"""
        return self.price


accounting/forms.py
# -*- coding: utf-8 -*-
# @Author: ZhuZefeng
# @Date:   2018-12-21 15:22:57
# @Last Modified by:   ZhuZefeng
# @Last Modified time: 2018-12-27 12:57:58


from django       import forms
from django.forms import widgets
from .models      import Order, Client

class OrderForm(forms.ModelForm):
    """用于创建销售订单的表单"""    
    class Meta:
        model  = Order
        fields = [  'number_of_purchase_contract', 
                    'number_of_client', 
                    'product', 
                    'date_of_sale', 
                    'service_life', 
                    'sales_amount', 
                    'tax_included_or_not', 
                    'invoiced_or_not', 
                    'number_of_invoiced', 
                    'closed_or_not',]

    '''
    number_of_purchase_contract = forms.CharField(label='订单编号')
    number_of_client            = forms.CharField(label='客户名称')
    product                     = forms.CharField(label='产品名称')
    date_of_sale                = forms.DateField(label='销售日期')
    service_life                = forms.IntegerField(label='使用期限')
    sales_amount                = forms.FloatField(label='销售金额')
    tax_included_or_not         = forms.IntegerField(label='是否含税', widget=forms.Select(choices=(('0','不含增值税'),('1','含增值税'))))
    invoiced_or_not             = forms.IntegerField(label='是否开票', widget=forms.Select(choices=(('0','未开发票'),('1','已开发票'))))
    number_of_invoiced          = forms.CharField(label='发票编号')
    closed_or_not               = forms.IntegerField(label='是否到期', widget=forms.Select(choices=(('0','未到期'),('1','已到期'))))
    '''


class ClientForm(forms.ModelForm):
    """用于创建添加客户的表单"""    
    class Meta:
        model  = Client
        fields = [  'number_of_client',
                    'name_of_client',
                    'taxpayer_identification_number',
                    'province',
                    'city',
                    'address',
                    'telephone',
                    'deposit_bank',
                    'bank_account',]

'''
class ProductForm(forms.ModelForm):
    """用于创建添加产品的表单"""    
    class Meta:
        model  = Client
        fields = [  'number_of_product',
                    'name_of_product',
                    'service_life',
                    'price',
                    'value_added_tax_rate',
                    'VAT_inclusive',]
'''

accounting/views.py
from django.shortcuts import render
from django.http      import HttpResponseRedirect
from django.urls      import reverse
from .models          import Order, Client, Product, Price
from .forms           import OrderForm, ClientForm

# Create your views here.
#在此处创建你的视图函数

def index(request):
    """accounting程序的主页"""
    return render(request, 'accounting/index.html')

def orders(request):
    """显示目前所有的销售订单"""
    orders = Order.objects.all()
    context = {'orders':orders}

    return render(request, 'accounting/orders.html', context)

def new_order(request):
    """创建新的销售订单"""
    if request.method != 'POST':
        #当操作为非提交数据时，则创建一个新的销售订单
        form = OrderForm()
    else:
        #当操作为提交数据时，则对数据进行处理
        form = OrderForm(request.POST)
        if form.is_valid():
            #保存数据
            form.save()
            return HttpResponseRedirect(reverse('accounting:orders'))

    context = {'form':form}

    return render(request, 'accounting/new_order.html', context)

def clients(request):
    """显示目前所有客户的信息"""
    clients = Client.objects.all()
    context = {'clients':clients}

    return render(request, 'accounting/clients.html', context)

def new_client(request):
    """添加新客户的信息"""
    if request.method != 'POST':
        #当操作为非提交数据时，则创建一个新的客户信息页面
        form = ClientForm()
    else:
        #当操作为提交数据时，则对数据进行处理
        form = ClientForm(request.POST)
        if form.is_valid():
            #保存数据
            form.save()
            return HttpResponseRedirect(reverse('accounting:clients'))

    context = {'form':form}

    return render(request, 'accounting/new_client.html', context)

def products(request):
    """显示目前所有产品的信息"""
    #获取所有产品的信息
    products = Product.objects.all()

    product_information =[]

    for product in products:
        pi = []
        #获取某产品的价格信息，按使用期限排序
        prices = product.price_set.order_by('service_life')
        #合并产品信息与价格信息
        pi= [product, prices]
        #获取所有产品信息及其价格信息
        product_information.append(pi)

    context  = {'product_information':product_information,}

    return render(request, 'accounting/products.html', context)
'''
def new_product(request):
    """添加新客户的信息"""
    if request.method != 'POST':
        #当操作为非提交数据时，则创建一个新的客户信息页面
        form = ProductForm()
    else:
        #当操作为提交数据时，则对数据进行处理
        form = ProductForm(request.POST)
        if form.is_valid():
            #保存数据
            form.save()
            return HttpResponseRedirect(reverse('accounting:products'))

    context = {'form':form}

    return render(request, 'accounting/new_product.html', context)
'''

accounting/templates/accounting/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>猎户座左旋臂</title>

        {% bootstrap_css %}
        {% bootstrap_javascript %}
    </head>

    <body>   
        <!-- Static navbar -->
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button"          class="navbar-toggle collapsed"
                            data-toggle="collapse" data-target="#navbar"
                            aria-expanded="false"  aria-controls="#navbar">                    
                    </button>

                    <a class="navbar-brand" href="{% url 'homepage:homepage' %}">
                        <b>Project Orion</b>
                    </a>
                </div>

                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'learning_logs:index' %}">学习日志</a></li>
                        <li><a href="{% url 'financial_indicator_library:index' %}">财务指标库</a></li>
                        <li><a href="{% url 'accounting:index' %}">账务处理</a></li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                            <li>
                                <a>{{ user.username }}</a>
                            </li>
                            <li>
                                <a href="{% url 'users:logout' %}">注销</a>
                            </li>
                        {% else %}
                            <li>
                                <a href="{% url 'users:register' %}">注册</a>
                            </li>
                            <li>
                                <a href="{% url 'users:login' %}">登录</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>                      
            </div>            
        </nav>

        <div class="container">
            <h5>
                <b>
                    <a href="{% url 'accounting:index' %}">首页</a> - 
                    <a href="{% url 'accounting:orders' %}">销售订单</a> - 
                    <a href="{% url 'accounting:clients' %}">客户信息</a> - 
                    <a href="{% url 'accounting:products' %}">产品信息</a> - 
                </b>
            </h5>
        </div>

        <div class="container">
            <div class="page-header">   
                {% block header %}
                {% endblock header %}  
            </div>
            
            <div class="page-body">
                {% block content %}
                {% endblock content %}
            </div>
        </dir>
    </body>
</html>


accounting/templates/accounting/clients.html
{% extends "accounting/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h3>
        <b>客户信息</b>
    </h3>
   
    <small>
        <a href="{% url 'accounting:new_client' %}">添加客户</a> 
    </small> 

{% endblock header %}

{% block content %}
    <DIV  class="panel panel-default">
        <table class="table table-hover">
            <thead>
                <tr class="info" >
                    <th style="text-align:center;">ID</th>
                    <th style="text-align:center;">客户编号</th>
                    <th style="text-align:center;">客户名称</th>
                    <th style="text-align:center;">纳税人识别号</th>
                    <th style="text-align:center;">省</th>
                    <th style="text-align:center;">市</th>
                    <th style="text-align:center;">详细地址</th>
                    <th style="text-align:center;">电话号码</th>
                    <th style="text-align:center;">开户银行</th>
                    <th style="text-align:center;">银行账号</th>
                </tr>
            </thead>

            <tbody>
                {% for client in clients %}
                    <tr>
                        <td style="vertical-align: middle; text-align: center;">{{ client.id }}</td>
                        <td style="vertical-align: middle; text-align: center;">{{ client.number_of_client }}</td>
                        <td style="vertical-align: middle; text-align: center;">{{ client.name_of_client }}</td>
                        <td style="vertical-align: middle; text-align: center;">{{ client.taxpayer_identification_number }}</td>
                        <td style="vertical-align: middle; text-align: center;">{{ client.province }}</td>
                        <td style="vertical-align: middle; text-align: center;">{{ client.city }}</td>
                        <td style="vertical-align: middle; text-align: center;">{{ client.address }}</td>
                        <td style="vertical-align: middle; text-align: center;">{{ client.telephone }}</td>
                        <td style="vertical-align: middle; text-align: center;">{{ client.deposit_bank }}</td>
                        <td style="vertical-align: middle; text-align: center;">{{ client.bank_account }}</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td style="vertical-align: middle" colspan="11" >
                            <!--第一个单元格与第二个单元格合并，colspan="11"意思是第一个单元格的长度改变成五个单元格的长度，也就是把第一个单元格长度边长五倍，第二个单元格的<td></td>删除。-->
                            尚未添加任何客户信息。
                        </td> 
                    </tr>
                {% endfor %}
            </tbody>   
        </table>
    </DIV>
{% endblock content %}

accounting/templates/accounting/index.html
{% extends "accounting/base.html" %}

{% block header%}
    <h2>
        <b>账务处理</b>
    </h2>
{% endblock header%}

{% block content %}
    <div >
        <h4>进行各项账务处理，如：</h4>
        <ul>
            <li>收入的分期确认；</li>                            
        </ul> 
    </div>    
{% endblock content %}

accounting/templates/accounting/new_client.html
{% extends "accounting/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h3>
        <b>添加客户信息</b>
    </h3>
{% endblock header %}

{% block content %} 
    <form action="{% url 'accounting:new_client' %}" method="POST" role="form">
        {% csrf_token %}

        <div class="col-md-10" style="text-align: right;">
            {% bootstrap_field form.number_of_client layout='horizontal' label='客户编号' placeholder='请输入客户编号' %}

            {% bootstrap_field form.name_of_client layout='horizontal' label='客户名称' placeholder='请输入客户名称' %}

            {% bootstrap_field form.taxpayer_identification_number layout='horizontal' label='客户纳税人识别号' placeholder='请输入客户纳税人识别号' %}

            {% bootstrap_field form.province layout='horizontal' label='客户所在省份' placeholder='请输入客户所在省份' %}

            {% bootstrap_field form.city layout='horizontal' label='客户所在城市' placeholder='请输入客户所在城市' %}

            {% bootstrap_field form.address layout='horizontal' label='客户详细地址' placeholder='请输入客户的详细地址' %}

            {% bootstrap_field form.telephone layout='horizontal' label='客户电话' placeholder='请输入客户电话' %}

            {% bootstrap_field form.deposit_bank layout='horizontal' label='开户银行' placeholder='请输入客户的开户银行' %}

            {% bootstrap_field form.bank_account layout='horizontal' label='银行账户' placeholder='请输入客户的银行开户账号' %}
        </div>

        <div class="col-md-12" style="text-align: center;">
            {% bootstrap_button "重新填写" button_type="reset" button_class="btn-primary" %}

            {% bootstrap_button "添加客户" button_type="submit" button_class="btn-primary" %}
        </div>
    </form>
    
{% endblock content %}

accounting/templates/accounting/new_order.html
{% extends "accounting/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h3>
        <b>添加销售订单</b>
    </h3>
{% endblock header %}

{% block content %}
    <!-- 使用bootstrap3创建表单
    <form action="{% url 'accounting:new_order' %}"  method="POST" class="form-horizontal" role="form" >
        {% csrf_token %}

        <div class="form-group">
            <label for="number_of_purchase_contract" class="col-sm-2 control-label">订单编号</label>
            <div class="col-sm-5">
                <input type="text" class="form-control" name="number_of_purchase_contract" placeholder="请输入订单编号">
            </div>
        </div>

        <div class="form-group">
            <label for="number_of_client" class="col-sm-2 control-label">客户名称</label>
            <div class="col-sm-5">
                <input type="text" class="form-control" name="number_of_client" placeholder="请选择客户">
            </div>
        </div>

        <div class="form-group">
            <label for="product" class="col-sm-2 control-label">产品名称</label>
            <div class="col-sm-5">
                <input type="text" class="form-control" name="product" placeholder="请选择产品">
            </div>
        </div>

        <div class="form-group">
            <label for="date_of_sale" class="col-sm-2 control-label">销售日期</label>
            <div class="col-sm-5">
                <input type="text" class="form-control" name="date_of_sale" placeholder="请输入销售日期">
            </div>
        </div>

        <div class="form-group">
            <label for="service_life" class="col-sm-2 control-label">使用期限</label>
            <div class="col-sm-5">
                <input type="text" class="form-control" name="service_life" placeholder="请输入使用期限">
            </div>
        </div>

        <div class="form-group">
            <label for="sales_amount" class="col-sm-2 control-label">销售金额</label>
            <div class="col-sm-5">
                <input type="text" class="form-control" name="sales_amount" placeholder="请输入销售金额">
            </div>
        </div>

        <div class="form-group">
            <label for="tax_included_or_not" class="col-sm-2 control-label">是否含税</label>
            <div class="col-sm-5">
                <select class="form-control" name="tax_included_or_not" value="0">
                    <option value="0">不含增值税</option>
                    <option value="1">含增值税</option>
                </select>
            </div>
        </div>

        <div class="form-group">
            <label for="invoiced_or_not" class="col-sm-2 control-label">是否开票</label>
            <div class="col-sm-5">
                <select class="form-control" name="invoiced_or_not" value="0">
                    <option value="0">未开发票</option>
                    <option value="1">已开发票</option>
                </select>
            </div>
        </div>

        <div class="form-group">
            <label for="number_of_invoiced" class="col-sm-2 control-label">发票编号</label>
            <div class="col-sm-5">
                <input type="text" class="form-control" name="number_of_invoiced" placeholder="请输入发票编号">
            </div>
        </div>

        <div class="form-group">
            <label for="closed_or_not" class="col-sm-2 control-label">是否到期</label>
            <div class="col-sm-5">
                <select class="form-control" name="closed_or_not" value="0">
                    <option value="0">未到期</option>
                    <option value="1">已到期</option>
                </select>
            </div>
        </div>

        {% buttons %}
            <button name="submit" class="btn btn-primary">添加</button> 
        {% endbuttons %}
    </form>
    -->
    

    <!-- 使用django的表单控件创建表单
    <form action="{% url 'accounting:new_order' %}"  method="POST" role="form" >
        {% csrf_token %}
    
        {% bootstrap_form form layout='horizontal' horizontal_label_class='col-md-1' horizontal_field_class='col-md-5' %}

        <div class="form-inline" style="vertical-align: middle" align="center">
            {% bootstrap_button "新增客户" button_type="button" button_class="btn-primary" %}
            {% bootstrap_button "新增产品" button_type="button" button_class="btn-primary" %}
            {% bootstrap_button "添加订单" button_type="submit" button_class="btn-primary" %}
        </div>  
    </form>
    --> 

    <!-- 使用django的字段控件创建表单--> 
    <form action="{% url 'accounting:new_order' %}" method="POST" role="form" >
        {% csrf_token %}

        <div class="col-md-10" style="text-align: right;">
            {% bootstrap_field form.number_of_purchase_contract layout='horizontal' label='订单编号' placeholder='请输入订单编号' %}

            {% bootstrap_field form.number_of_client layout='horizontal' label='客户名称' placeholder='请选择客户' %}

            {% bootstrap_field form.product layout='horizontal' label='产品名称' placeholder='请选择产品' %}

            {% bootstrap_field form.date_of_sale layout='horizontal' label='销售日期' placeholder='请输入销售日期' %}

            {% bootstrap_field form.service_life layout='horizontal' label='使用期限' placeholder='请输入使用期限' %}

            {% bootstrap_field form.sales_amount layout='horizontal' label='销售金额' placeholder='请输入销售金额' %}

            {% bootstrap_field form.tax_included_or_not layout='horizontal' label='是否含税' %}

            {% bootstrap_field form.invoiced_or_not layout='horizontal' label='是否开票' %}

            {% bootstrap_field form.number_of_invoiced layout='horizontal' label='发票编号' placeholder='请输入发票编号' %}

            {% bootstrap_field form.closed_or_not layout='horizontal' label='是否到期' %}
        </div>

        <div class="col-md-12" style="text-align: center;">
            {% bootstrap_button "重新填写" button_type="reset" button_class="btn-primary" %}
            
            {% bootstrap_button "添加订单" button_type="submit" button_class="btn-primary" %}
        </div>
    </form>   
{% endblock content %}

accounting/templates/accounting/new_product.html
{% extends "accounting/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h3>
        <b>添加产品信息</b>
    </h3>
{% endblock header %}

{% block content %} 
    <form action="{% url 'accounting:new_product' %}" method="POST" role="form">
        {% csrf_token %}

        <div class="col-md-10" style="text-align: right;">
            {% bootstrap_field form.number_of_product layout='horizontal' label='产品编号' placeholder='请输入产品编号' %}

            {% bootstrap_field form.name_of_product layout='horizontal' label='产品名称' placeholder='请输入产品名称' %}

            {% bootstrap_field form.service_life layout='horizontal' label='使用期限' placeholder='请输入使用期限' %}

            {% bootstrap_field form.price layout='horizontal' label='客户所在省份' placeholder='请输入客户所在省份' %}

            {% bootstrap_field form.value_added_tax_rate layout='horizontal' label='客户所在城市' placeholder='请输入客户所在城市' %}

            {% bootstrap_field form.VAT_inclusive layout='horizontal' label='客户详细地址' placeholder='请输入客户的详细地址' %}
        </div>

        <div class="col-md-12" style="text-align: center;">
            {% bootstrap_button "重新填写" button_type="reset" button_class="btn-primary" %}

            {% bootstrap_button "添加客户" button_type="submit" button_class="btn-primary" %}
        </div>
    </form>
    
{% endblock content %}

accounting/templates/accounting/orders.html
{% extends "accounting/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h3>
        <b>销售订单</b>
    </h3>
        
    <small>
        <a href="{% url 'accounting:new_order' %}">添加销售订单</a> 
    </small>
{% endblock header %}

{% block content %}
    <DIV  class="panel panel-default">
        <table class="table table-hover">
            <thead>
                <tr class="info" >
                    <th style="text-align:center;" nowrap >ID</th>
                    <th style="text-align:center;" nowrap >采购合同编号</th>
                    <th style="text-align:center;" nowrap >客户编号</th>
                    <th style="text-align:center;" nowrap >产品名称</th>
                    <th style="text-align:center;" nowrap >销售日期</th>
                    <th style="text-align:center;" nowrap >使用期限</th>
                    <th style="text-align:center;" nowrap >销售金额</th>
                    <th style="text-align:center;" nowrap >是否含税</th>
                    <th style="text-align:center;" nowrap >是否开票</th>
                    <th style="text-align:center;" nowrap >发票编号</th>
                    <th style="text-align:center;" nowrap >是否完成</th>
                </tr>
            </thead>

            <tbody>
                {% for order in orders %}
                    <tr>
                        <td style="vertical-align: middle" align="center" >{{ order.id }}</td>
                        <td style="vertical-align: middle" align="center" >{{ order.number_of_purchase_contract }}</td>
                        <td style="vertical-align: middle" align="center" >{{ order.number_of_client }}</td>
                        <td style="vertical-align: middle" align="center" >{{ order.product }}</td>
                        <td style="vertical-align: middle" align="center" >{{ order.date_of_sale }}</td>
                        <td style="vertical-align: middle" align="center" >{{ order.service_life }}</td>
                        <td style="vertical-align: middle" align="center" >{{ order.sales_amount }}</td>
                        <td style="vertical-align: middle" align="center" >{% if order.tax_included_or_not %}含增值税{% else %}不含增值税{% endif %}</td>
                        <td style="vertical-align: middle" align="center" >{% if order.invoiced_or_not %}已开票{% else %}未开票{% endif %}</td>
                        <td style="vertical-align: middle" align="center" >{{ order.number_of_invoiced }}</td>
                        <td style="vertical-align: middle" align="center" >{% if order.closed_or_not %}已到期{% else %}未到期{% endif %}</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td style="vertical-align: middle" colspan="11" >
                            <!--第一个单元格与第二个单元格合并，colspan="11"意思是第一个单元格的长度改变成五个单元格的长度，也就是把第一个单元格长度边长五倍，第二个单元格的<td></td>删除。-->
                            尚未添加任何销售订单。
                        </td> 
                    </tr>
                {% endfor %}
            </tbody>   
        </table>
    </DIV>
{% endblock content %}

accounting/templates/accounting/products.html
{% extends "accounting/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h3>
        <b>产品信息</b>
    </h3>
   
     

{% endblock header %}

{% block content %}
    <DIV  class="panel panel-default">
        <table class="table table-hover">
            <thead>
                <tr class="info" >
                    <th style="text-align:center;">产品编号</th>
                    <th style="text-align:center;">产品名称</th>
                    <th style="text-align:center;">使用期限</th>
                    <th style="text-align:center;">价    格</th>
                    <th style="text-align:center;">适用增值税税率</th>
                </tr>
            </thead>

            <tbody>
                {% for pi in product_information %}
                    {% for price in pi.1 %}
                        <tr>
                            <td style="vertical-align: middle; text-align: center;">{{ pi.0.number_of_product }}</td>
                            <td style="vertical-align: middle; text-align: center;">{{ pi.0.name_of_product }}</td>
                            <td style="vertical-align: middle; text-align: center;">{{ price.service_life }}</td>
                            <td style="vertical-align: middle; text-align: center;">{{ price.price }}</td>
                            <td style="vertical-align: middle; text-align: center;">{{ pi.0.value_added_tax_rate }}</td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td style="vertical-align: middle; text-align: center;">{{ pi.0.number_of_product }}</td>
                            <td style="vertical-align: middle; text-align: center;">{{ pi.0.name_of_product }}</td>
                            <td style="vertical-align: middle; text-align: center;"> - </td>
                            <td style="vertical-align: middle; text-align: center;"> - </td>
                            <td style="vertical-align: middle; text-align: center;">{{ pi.0.value_added_tax_rate }}</td>
                        </tr>
                    {% endfor %}
                {% empty %}
                    <tr>
                        <td style="vertical-align: middle" colspan="7" >
                            <!--第一个单元格与第二个单元格合并，colspan="7"意思是第一个单元格的长度改变成五个单元格的长度，也就是把第一个单元格长度边长五倍，第二个单元格的<td></td>删除。-->
                            尚未添加任何产品信息。
                        </td> 
                    </tr>
                {% endfor %}
            </tbody>   
        </table>
    </DIV>
{% endblock content %}