financial_indicator_library/urls.py
# -*- coding: utf-8 -*-
# @Author: ZhuZefeng
# @Date:   2018-11-15 17:54:51
# @Last Modified by:   ZhuZefeng
# @Last Modified time: 2018-11-20 17:04:35


"""
为应用程序financial_indicator_library定义URL模式
"""

from django.urls import path, re_path
from .           import views

app_name = 'financial_indicator_library'

urlpatterns = [
               #financial_indicator_library的主页
               path('', views.index, name='index'),

               #显示目前所有收集的财务指标的页面
               path('indicators', views.indicators, name='indicators'),

               #显示各行业关键财务指标的平均水平的页面             
               path('average', views.average, name='average'),
              ]

homepage/urls.py
# -*- coding: utf-8 -*-
# @Author: ZhuZefeng
# @Date:   2018-11-12 12:40:26
# @Last Modified by:   ZhuZefeng
# @Last Modified time: 2018-11-12 12:40:40


"""
为应用程序lhomepage定义URL模式
"""

from django.urls import path
from .           import views

app_name = 'homepage'

urlpatterns = [
               #网站的主页
               path('',views.homepage, name='homepage'),
              ]

project_orion/urls.py
from django.contrib import admin
from django.urls    import path, include

urlpatterns = [
               path('', include('homepage.urls', namespace='homepage')),
               path('admin/', admin.site.urls),
               path('users/', include('users.urls', namespace='users')),
               path('learning_logs/', include('learning_logs.urls', namespace='learning_logs')),
               path('financial_indicator_library/', include('financial_indicator_library.urls', namespace='financial_indicator_library')),
               path('accounting/', include('accounting.urls', namespace='accounting')),
              ]

users/urls.py
# -*- coding: utf-8 -*-
# @Author: ZhuZefeng
# @Date:   2018-11-01 16:59:13
# @Last Modified by:   ZhuZefeng
# @Last Modified time: 2018-11-02 18:09:50


"""为应用程序users定义URL模式"""
from django.contrib.auth.views import LoginView
from django.urls               import path
from .                         import views

app_name = 'users'

urlpatterns = [
               # 登录页面
               path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),

               #注销页面
               path('logout', views.logout_view, name='logout'),

               #注册页面
               path('register', views.register, name='register'),

              ]

financial_indicator_library/models.py
from django.db                  import models

# Create your models here.
#在此处创建你的模型。


class TypeOfEnterprise(models.Model):
    """企业的类型"""
    type_of_enterprise = models.CharField(max_length=20)

    def __str__(self):
        """返回模型的值"""
        return self.type_of_enterprise


class BusinessScale(models.Model):
    """企业的规模"""
    business_scale = models.CharField(max_length=10)

    def __str__(self):
        """返回模型的值"""
        return self.business_scale


class BusinessStatus(models.Model):
    """企业的状况"""
    business_status = models.CharField(max_length=5)

    class Meta:
        verbose_name_plural = 'BusinessStatus'

    def __str__(self):
        """返回模型的值"""
        return self.business_status


class TypeOfIndicator(models.Model):
    """指标类型"""
    type_of_indicators_zh = models.CharField(max_length=20)
    type_of_indicators_en = models.CharField(max_length=40)

    def __str__(self):
        """返回模型的值"""
        return self.type_of_indicators_zh


class Indicator(models.Model):
    """指标库"""
    indicator_type        = models.ForeignKey(TypeOfIndicator, on_delete=models.CASCADE)
    indicator_name_zh     = models.CharField(max_length=50)
    indicator_name_en     = models.CharField(max_length=100)
    indicator_short_name  = models.CharField(max_length=10)
    unit_of_measurement   = models.CharField(max_length=10)
    indicator_description = models.CharField(max_length=300)

    def __str__(self):
        """返回模型的值"""
        return self.indicator_name_zh


class IndicatorData(models.Model):
    """指标数据"""
    te      = models.ForeignKey(TypeOfEnterprise, on_delete=models.CASCADE)
    bs      = models.ForeignKey(BusinessScale, on_delete=models.CASCADE)
    bss     = models.ForeignKey(BusinessStatus, on_delete=models.CASCADE)
    roe     = models.CharField(max_length=20)
    rota    = models.CharField(max_length=20)
    ros     = models.CharField(max_length=20)
    scsm    = models.CharField(max_length=20)
    rpce    = models.CharField(max_length=20)
    roc     = models.CharField(max_length=20)
    tat     = models.CharField(max_length=20)
    art     = models.CharField(max_length=20)
    bar     = models.CharField(max_length=20)
    cat     = models.CharField(max_length=20)
    cra     = models.CharField(max_length=20)
    alr     = models.CharField(max_length=20)
    ntie    = models.CharField(max_length=20)
    qr      = models.CharField(max_length=20)
    cfcr    = models.CharField(max_length=20)
    ibdr    = models.CharField(max_length=20)
    clr     = models.CharField(max_length=20)
    sgr     = models.CharField(max_length=20)
    cpar    = models.CharField(max_length=20)
    opgr    = models.CharField(max_length=20)
    tagr    = models.CharField(max_length=20)
    tir     = models.CharField(max_length=20)
    it      = models.CharField(max_length=20)
    tgapca  = models.CharField(max_length=20)
    cepoi   = models.CharField(max_length=20)
    evar    = models.CharField(max_length=20)
    ebitdar = models.CharField(max_length=20)
    car     = models.CharField(max_length=20)

    class Meta:
        verbose_name_plural = 'IndicatorData'

    def __str__(self):
        """返回模型的值"""
        return str(self.te) + "-" + str(self.bs) + "-" + str(self.bss)

financial_indicator_library/forms.py
# -*- coding: utf-8 -*-
# @Author: ZhuZefeng
# @Date:   2018-11-22 10:35:08
# @Last Modified by:   ZhuZefeng
# @Last Modified time: 2018-12-21 20:03:57


from django  import forms
from .models import TypeOfEnterprise, BusinessScale, BusinessStatus, IndicatorData

class AverageForm(forms.Form):
    """定义从企业类型、企业规模及企业状况表中读取数据供用户查询"""
    #创建下拉选择框，值为数字，将id传到后台处理 
    te  = forms.IntegerField(label='企业类型', widget=forms.Select())
    bs  = forms.IntegerField(label='企业规模', widget=forms.Select())
    bss = forms.IntegerField(label='企业状况', widget=forms.Select())

    def __init__(self, *args, **kwargs):
        super(AverageForm, self).__init__(*args, **kwargs)
        #从企业类型表中读取全部数据
        self.fields['te'].widget.choices  = TypeOfEnterprise.objects.all().values_list('id', 'type_of_enterprise')
        self.fields['bs'].widget.choices  = BusinessScale.objects.all().values_list('id', 'business_scale')
        self.fields['bss'].widget.choices = BusinessStatus.objects.all().values_list('id', 'business_status')

financial_indicator_library/views.py
from django.shortcuts import render
from django.http      import HttpResponseRedirect
from django.urls      import reverse
from .models          import Indicator, TypeOfEnterprise, BusinessScale, BusinessStatus, IndicatorData
from .forms           import AverageForm


# Create your views here.
#在此处创建你的视图函数

def index(request):
    """financial_indicator_library网站的主页"""
    return render(request, 'financial_indicator_library/index.html')


def indicators(request):
    """显示目前已收集的所有财务指标"""
    indicators = Indicator.objects.all()
    context = {'indicators':indicators}

    return render(request, 'financial_indicator_library/indicators.html', context)


def average(request):
    """显示各行业关键财务指标的平均水平"""
    indicator_data = IndicatorData()

    if request.method != 'POST':
        #当操作为非提交数据时，则创建一个新的表单
        form = AverageForm()
    else:
        #当操作为提交数据时，则对数据进行处理
        form = AverageForm(request.POST)

        if form.is_valid():        
            #获取post数据all_data['te']
            all_data = form.clean()
            te  = all_data['te']
            bs  = all_data['bs']
            bss = all_data['bss']

            indicator_data = IndicatorData.objects.get(te=te, bs=bs, bss=bss)

    context = {"form":form, "indicator_data":indicator_data}

    return render(request, 'financial_indicator_library/average.html', context)

financial_indicator_library/templates/financial_indicator_library/average.html
{% extends "financial_indicator_library/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h3>
        <b>关键财务指标平均水平</b>
    </h3>
{% endblock header %}

{% block content %}
    <form action="{% url 'financial_indicator_library:average' %}"  method="POST" role="form">
        {% csrf_token %}
            
        {% bootstrap_field form.te layout='horizontal' horizontal_label_class='col-sm-1' horizontal_field_class='col-sm-3' %}

        {% bootstrap_field form.bs layout='horizontal' horizontal_label_class='col-sm-1' horizontal_field_class='col-sm-2' %}

        {% bootstrap_field form.bss layout='horizontal' horizontal_label_class='col-sm-1' horizontal_field_class='col-sm-2' %}

        {% bootstrap_button "查询" button_type="submit" button_class="btn-primary" %} 
    </form>

    <p></p>

    <div>
        <ul id="myTab" class="nav nav-tabs">
            <li class="active"><a href="#profitability_indicators" data-toggle="tab">盈利能力指标</a></li>
            <li><a href="#asset_quality_indicators" tabindex="-1" data-toggle="tab">资产质量指标</a></li>
            <li><a href="#debt_risk_indicators" data-toggle="tab">债务风险指标</a></li>
            <li><a href="#business_growth_indicator" data-toggle="tab">经营增长指标</a></li>
            <li class="dropdown">
                <a href="#" id="other_indicators" class="dropdown-toggle" data-toggle="dropdown">其他指标<b class="caret"></b></a>
                <ul class="dropdown-menu" role="menu" aria-labelledby="other_indicators">
                    <li><a href="#other_indicator_one" tabindex="-1" data-toggle="tab">其他指标1</a></li>
                    <li><a href="#other_indicator_two" tabindex="-1" data-toggle="tab">其他指标2</a></li>
                </ul>
            </li>
        </ul>

        <div id="myTabContent" class="tab-content">
            <div class="tab-pane in active" id="profitability_indicators" width="250px">
                <table class="table table-hover" style="table-layout: fixed;">
                    <tr class="success"><th>指标名称</th><th style="text-align:center;">平均值</th></tr>
                    <tr><td>净资产收益率</td>      <td style="text-align:center;">{{ indicator_data.roe  }}</td></tr>
                    <tr><td>总资产报酬率</td>      <td style="text-align:center;">{{ indicator_data.rota }}</td></tr>
                    <tr><td>销售（营业）利润率</td><td style="text-align:center;">{{ indicator_data.ros  }}</td></tr>
                    <tr><td>盈余现金保障倍数</td>  <td style="text-align:center;">{{ indicator_data.scsm }}</td></tr>
                    <tr><td>成本费用利润率</td>    <td style="text-align:center;">{{ indicator_data.rpce }}</td></tr>
                    <tr><td>资本收益率</td>        <td style="text-align:center;">{{ indicator_data.roc  }}</td></tr>
                </table>
            </div>

            <div class="tab-pane" id="asset_quality_indicators" width="250px">
                <table class="table table-hover" style="table-layout: fixed;">
                    <tr class="success"><th >指标名称</th> <th style="text-align:center;">平均值</th></tr>
                    <tr><td>总资产周转率</td>      <td style="text-align:center;">{{ indicator_data.tat }}</td></tr>
                    <tr><td>应收账款周转率</td>    <td style="text-align:center;">{{ indicator_data.art }}</td></tr>
                    <tr><td>不良资产比率</td>      <td style="text-align:center;">{{ indicator_data.bar }}</td></tr>
                    <tr><td>流动资产周转率</td>    <td style="text-align:center;">{{ indicator_data.cat }}</td></tr>
                    <tr><td>资产现金回收率</td>    <td style="text-align:center;">{{ indicator_data.cra }}</td></tr>
                </table>
            </div>

            <div class="tab-pane" id="debt_risk_indicators" width="250px">
                <table class="table table-hover" style="table-layout: fixed;">
                    <tr class="success"><th >指标名称</th> <th style="text-align:center;">平均值</th></tr>
                    <tr><td>资产负债率</td>        <td style="text-align:center;">{{ indicator_data.alr  }}</td></tr>
                    <tr><td>已获利息倍数</td>      <td style="text-align:center;">{{ indicator_data.ntie }}</td></tr>
                    <tr><td>速动比率</td>          <td style="text-align:center;">{{ indicator_data.qr   }}</td></tr>
                    <tr><td>现金流动负债比率</td>  <td style="text-align:center;">{{ indicator_data.cfcr }}</td></tr>
                    <tr><td>带息负债比率</td>      <td style="text-align:center;">{{ indicator_data.ibdr }}</td></tr>
                    <tr><td>或有负债比率</td>      <td style="text-align:center;">{{ indicator_data.clr  }}</td></tr>
                </table>
            </div>

            <div class="tab-pane" id="business_growth_indicator" width="250px">
                <table class="table table-hover" style="table-layout: fixed;">
                    <tr class="success"><th>指标名称</th> <th style="text-align:center;">平均值</th></tr>
                    <tr><td>销售增长率</td>     <td style="text-align:center;">{{ indicator_data.sgr  }}</td></tr>
                    <tr><td>资本保值增值率</td> <td style="text-align:center;">{{ indicator_data.cpar }}</td></tr>
                    <tr><td>营业利润增长率</td> <td style="text-align:center;">{{ indicator_data.opgr }}</td></tr>
                    <tr><td>总资产增长率</td>   <td style="text-align:center;">{{ indicator_data.tagr }}</td></tr>
                    <tr><td>技术投入比率</td>   <td style="text-align:center;">{{ indicator_data.tir  }}</td></tr>
                </table>
            </div>

            <div class="tab-pane" id="other_indicator_one"  width="250px">
                <table class="table table-hover"  style="table-layout: fixed;">
                    <tr class="success"><th >指标名称</th> <th style="text-align:center;">平均值</th></tr>
                    <tr><td>存货周转率</td>     <td style="text-align:center;">{{ indicator_data.it }}</td></tr>
                    <tr><td>两金占流动资产比重</td><td style="text-align:center;">{{ indicator_data.tgapca }}</td></tr>
                    <tr><td>成本费用占营业收入比重</td><td style="text-align:center;">{{ indicator_data.cepoi }}</td></tr>
                    <tr><td>经济增加值率</td>   <td style="text-align:center;">{{ indicator_data.evar }}</td></tr>
                    <tr><td>EBITDA率</td>       <td style="text-align:center;">{{ indicator_data.ebitdar }}</td></tr>
                    <tr><td>资本积累率</td>     <td style="text-align:center;">{{ indicator_data.car }}</td></tr>
                </table>
            </div>

            <div class="tab-pane" id="other_indicator_two">
                <p>其他指标二</p>
            </div>
        </div> 
    </div>
{% endblock content %}

financial_indicator_library/templates/financial_indicator_library/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>猎户座左旋臂</title>

        {% bootstrap_css %}
        {% bootstrap_javascript %}
    </head>

    <body>   
        <!-- Static navbar -->
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button"          class="navbar-toggle collapsed"
                            data-toggle="collapse" data-target="#navbar"
                            aria-expanded="false"  aria-controls="#navbar">                    
                    </button>

                    <a class="navbar-brand" href="{% url 'homepage:homepage' %}">
                        <b>Project Orion</b>
                    </a>
                </div>

                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="{% url 'learning_logs:index' %}">学习日志</a>
                        </li>
                        <li>
                            <a href="{% url 'financial_indicator_library:index' %}">财务指标库</a>
                        </li>
                        <li>
                            <a href="{% url 'accounting:index' %}">账务处理</a>
                        </li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                            <li>
                                <a>{{ user.username }}</a>
                            </li>
                            <li>
                                <a href="{% url 'users:logout' %}">注销</a>
                            </li>
                        {% else %}
                            <li>
                                <a href="{% url 'users:register' %}">注册</a>
                            </li>
                            <li>
                                <a href="{% url 'users:login' %}">登录</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>                      
            </div>            
        </nav>

        <div class="container">
            <h5>
                <b>
                    <a href="{% url 'financial_indicator_library:index' %}">首页</a> - 
                    <a href="{% url 'financial_indicator_library:indicators' %}">财务指标</a> - 
                    <a href="{% url 'financial_indicator_library:average' %}">平均水平</a>
                </b>
            </h5>
        </div>

        <div class="container">
            <div class="page-header">   
                {% block header %}
                {% endblock header %}  
            </div>
            
            <div class="page-body">
                {% block content %}
                {% endblock content %}
            </div>
        </dir>
    </body>
</html>


financial_indicator_library/templates/financial_indicator_library/index.html
{% extends "financial_indicator_library/base.html" %}

{% block header%}
    <h2>
        <b>财务指标库</b>
    </h2>
{% endblock header%}

{% block content %}
    <div >
        <ul>
            <li>
                <h4>展示各项财务指标</h4>
            </li>
            <li>
                <h4>行业关键财务指标平均水平</h4>
            </li>            
        </ul> 
    </div>    
{% endblock content %}

financial_indicator_library/templates/financial_indicator_library/indicators.html
{% extends "financial_indicator_library/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h3>
        <b>财务指标</b>
    </h3>
        
    <small>
        <a href="{% url 'financial_indicator_library:indicators' %}">添加财务指标</a> 
    </small>
{% endblock header %}

{% block content %}
    <DIV  class="panel panel-default">
        <table class="table table-hover">
            <thead>
                <tr class="info" style="text-align:center;">
                    <th  nowrap >序号</th>
                    <th >指标类型</th>
                    <th>指标名称</b></th>
                    <th>计量单位</th>
                    <th>指标描述</th>
                </tr>
            </thead>

            <tbody>
                {% for indicator in indicators %}
                    <tr>
                        <td style="vertical-align: middle; text-align: center;">{{ indicator.id }}</td>
                        <td style="vertical-align: middle; text-align: center;">{{ indicator.indicator_type }}</td>
                        <td style="vertical-align: middle; text-align: center;">{{ indicator.indicator_name_zh }}</td>
                        <td style="vertical-align: middle; text-align: center;">{{ indicator.unit_of_measurement }}</td>
                        <td style="vertical-align: middle; text-align: left;">{{ indicator.indicator_description }}</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td style="vertical-align: middle" colspan="5">
                            <!--第一个单元格与第二个单元格合并，colspan="5"意思是第一个单元格的长度改变成五个单元格的长度，也就是把第一个单元格长度边长五倍，第二个单元格的<td></td>删除。-->
                            <b>尚未添加任何财务指标。</b>
                        </td> 
                    </tr>
                {% endfor %}
            </tbody>   
        </table>
    </DIV>
{% endblock content %}